### ISSUE TITLE
Comparison of detection performance in sensor missing scenarios

### ISSUE THREAD

**Issue by dingmiaomiao** [hanchaa/MEFormer#1]
Thanks for your work! In Table 2, models can get more than 42.0 with mask-modal strategy (ModalMask3D) when the LiDAR sensor is missing. But I added "ModalMask3D" to bevfusion and my model, the result only is 0.25. Can you provide more details on technology or point out some errors in my operations?

**Comment by hanchaa** [comment]
Hi @dingmiaomiao, thank you for your interest in our work.

We didn't use ModalMask3D in training, as shown in the configs ([MOAD](https://github.com/hanchaa/MEFormer/blob/main/projects/configs/moad_voxel0075_vov_1600x640_cbgs.py#L34), [PME](https://github.com/hanchaa/MEFormer/blob/main/projects/configs/meformer_voxel0075_vov_1600x640_cbgs.py#L34)).
Can you explain your question in more detail?

**Comment by dingmiaomiao** [comment]
Thank you for your reply. In Table 2 of your paper, the NDS for the "camera only" experiment reached 48.0, while the accuracy of CMT and MetaBEV as comparison methods were 42.6 and 44.7, respectively. Both the CMT and MetaBEV papers used [ModalMask3D](https://github.com/hanchaa/MEFormer/blob/f93719a0a98c9261e0149a475327b203b0807f4d/projects/mmdet3d_plugin/datasets/pipelines/transform_3d.py#L835) to handle the case where one sensor is missing. Did your paper also use this approach, or could you provide the corresponding config and specific operations for the results in Table 2?

**Comment by hanchaa** [comment]
For the result of Table 2, we do not use the ModalMask3D.
Instead, we use Modality-Agnostic Decoding dubbed MOAD, which is our proposed method in Section 3.2.
You can check the config [here](https://github.com/hanchaa/MEFormer/blob/main/projects/configs/moad_voxel0075_vov_1600x640_cbgs.py).
After training the MOAD, to test the sensor missing scenario, you can change the test modality in [L244](https://github.com/hanchaa/MEFormer/blob/main/projects/configs/moad_voxel0075_vov_1600x640_cbgs.py#L244) to 'bev' for LiDAR only or 'img' for camera only.

**Comment by dingmiaomiao** [comment]
OK ! Thanks for your reply.
