### ISSUE TITLE
Robustness Benchmark

### ISSUE THREAD

**Issue by TillBeemelmanns** [hanchaa/MEFormer#2]
Hi !

Thank you for this excellent work! I just ran MEFormer on our [MultiCorrupt](https://github.com/ika-rwth-aachen/MultiCorrupt) benchmark to asses the robustness of the approach and I am happy to report that the MEFormer configuration with PME outperforms currently all tested models in this benchmark. Congratulations! 

| Model                                                           | Clean     | Beams Red.   | Brightness   | Darkness   | Fog       | Missing Cam.   | Motion Blur   | Points Red.   | Snow       | Spatial Mis.   | Temporal Mis.   | mRRA      |
|:----------------------------------------------------------------|:----------|:-------------|:-------------|:-----------|:----------|:---------------|:--------------|:--------------|:-----------|:---------------|:----------------|:----------|
| ⭐ [MEFormer](https://github.com/hanchaa/MEFormer)                 | **0.739** | 16.759       | 0.878        | 1.556      | 8.586     | -0.168         | -0.307        | **8.865**     | **11.382** | 16.689         | **9.668**       | **7.391** |
| [CMT](https://github.com/junjie18/CMT)                          | 0.729     | **18.642**   | -1.138       | -0.096     | **9.398** | **2.041**      | -0.841        | 8.213         | 9.887      | **17.053**     | 8.448           | 7.161     |
| [MEFormer w/o PME](https://github.com/hanchaa/MEFormer)         | 0.737     | 15.172       | 0.714        | 1.522      | 8.176     | -0.791         | -0.679        | 8.384         | 10.749     | 14.968         | 9.184           | 6.740     |
| [Sparsefusion](https://github.com/yichen928/SparseFusion)       | 0.732     | 4.264        | **3.179**    | **1.821**  | 4.429     | 0.297          | 0.280         | 3.242         | 1.887      | 3.699          | 7.228           | 3.033     |
| [IS-Fusion](https://github.com/yinjunbo/IS-Fusion)              | 0.737     | 3.684        | 2.291        | 1.267      | 3.890     | 0.920          | **3.994**     | 1.691         | -2.351     | 4.513          | 7.177           | 2.708     |
| ⚓︎ [BEVfusion](https://github.com/mit-han-lab/bevfusion)           | 0.714     | 0.000        | 0.000        | 0.000      | 0.000     | 0.000          | 0.000         | 0.000         | 0.000      | 0.000          | 0.000           | 0.000     |
| [TransFusion](https://github.com/XuyangBai/TransFusion)         | 0.708     | -7.210       | 1.799        | 1.146      | -0.552    | 0.340          | -5.412        | -3.296        | -4.220     | -3.626         | 3.850           | -1.718    |
| [UniBEV_avg](https://github.com/tudelft-iv/UniBEV)              | 0.684     | 7.617        | -3.758       | -4.595     | -1.228    | -5.170         | -11.777       | -0.144        | -6.909     | 2.812          | 1.617           | -2.154    |
| [UniBEV_cat](https://github.com/tudelft-iv/UniBEV)              | 0.678     | 6.534        | -4.303       | -5.279     | -0.199    | -5.438         | -12.505       | -0.979        | -6.596     | 1.436          | 0.799           | -2.653    |
| [UniBEV_cnw](https://github.com/tudelft-iv/UniBEV)              | 0.685     | 5.030        | -3.729       | -4.383     | -1.104    | -5.749         | -13.119       | -0.428        | -8.055     | 1.582          | 1.025           | -2.893    |
| [DeepInteraction](https://github.com/fudan-zvg/DeepInteraction) | 0.691     | -6.361       | -3.150       | -7.215     | -25.037   | -16.386        | -7.077        | -2.188        | -5.149     | 0.212          | 0.145           | -7.221    |

Best,
Till Beemelmanns

**Comment by hanchaa** [comment]
Thank you for giving us good news!
We appreciate your work and will consider your benchmarks for our next work.

Best regards,
Juhan Cha
