### ISSUE TITLE
"Regarding the PME module"

### ISSUE THREAD

**Issue by Neko-coffee** [hanchaa/MEFormer#3]
Great work! I’ve just started working in this area and am very interested in your PME module. I would like to ask where the specific implementation code for the PME module is located. I noticed that you tested the accuracy of MEFormer and CMT with and without the PME module applied. Does this mean that the module can be integrated into the original network with minimal modification? Could you explain this in more detail? My research is also related to robustness, and I’ve already replicated the CMT code for my work. Therefore, I would appreciate it if you could share how exactly you applied the PME module.

**Comment by hanchaa** [comment]
I appreciate your interest in our work!

The code of PME module is located in [here](https://github.com/hanchaa/MEFormer/blob/main/projects/mmdet3d_plugin/models/utils/pme_transformer.py).
Also, config fore PME module can be found [here](https://github.com/hanchaa/MEFormer/blob/main/projects/configs/meformer_voxel0075_vov_1600x640_cbgs.py#L262).

The PME module can be used with CMT, but requires some modifications to CMT.
If you need any more help, feel free to ask us.

**Comment by Neko-coffee** [comment]
Thank you very much for your patient response! Based on my understanding, should I just change type='CmtTransformer' to type='PMETransformer' in the config file? Are there any other adjustments I need to be aware of? 
Additionally, if there are other similar models, can they also be replaced in the same way?
I’m new to this field, so my understanding may not be fully thorough yet. If there are any other details I should pay attention to, I would really appreciate your guidance. Thank you for your help

**Comment by hanchaa** [comment]
No, you should use both 'CmtTransformer' and 'PMETransformer'.
'PMETransformer' is an add-on module.

You can reimplement CMT with MEFormer codes by following the below instructions.
1. Go to [MOAD config](https://github.com/hanchaa/MEFormer/blob/main/projects/configs/moad_voxel0075_vov_1600x640_cbgs.py)
2. In line 243, change `train=["fused", "bev", "img"]` to `train=["fused"]`
3. In line 266, change `use_cam_embed=True` to `use_cam_embed=False`
4. Add `use_type_embed=False` in line 267

Then the code works the same as CMT, and if you load CMT's pre-trained weights, you will see the same mAP and NDS as CMT.
Feel free to ask us if there is another issue!

**Comment by Neko-coffee** [comment]
Thank you very much for your patient guidance. After carefully reviewing the related code based on your explanation, I now have a general understanding of the workflow of the PME module. Once again, I appreciate your help, and I hope there will be more opportunities to communicate with you in the future. I also wish you continued success in your work.
